export const experiences = [
  {
    title: "Highly Succeed Inc.",
    role: "Full-Stack Developer (Frontend Focused)",
    period: "Apr 2025 - Apr 2026 · 1 yr 1 mo",
    location: "Mandaluyong, National Capital Region, Philippines · Remote",
    type: "Full-time",
    description:
      "Responsible for building responsive and visually appealing web applications by collaborating with designers to translate wireframes and mockups into fully functional websites. Focused on creating reusable components and ensuring the technical feasibility of UI/UX designs while optimizing applications for performance and scalability. Conduct code reviews, troubleshoot issues, and stay updated with the latest trends and technologies in front-end development. Work closely with back-end developers to integrate user-facing elements with server-side logic.",
    projects: [
      "Go Negosyo MBA Learning Management System",
      "Unleash PH Admin Portal",
      "Unleash E-commerce website",
      "Unleash Landing Page",
      "Makati Waste Management System Admin Portal",
      "Plant AI – Admin Panel",
      "Night Pulse – Admin and LED Screen Dashboard",
      "Mobile App Development - Flutter enhancements",
      "NextSys IT Solutions Website",
    ],
    skills: [
      "React.js",
      "Next.js 15 - 16",
      "TypeScript",
      "Express.js",
      "Node.js",
      "Flutter",
      "RESTful APIs",
      "Socket.io",
    ],
  },
  {
    title: "Nuclear Brain",
    role: "Back End Developer",
    period: "May 2025 - Sep 2025 · 5 mos",
    location: "United States · Remote",
    type: "Part-time",
    description:
      "NodeJS version upgrade for ExpressJS Website—optimization for schemas and queries.",
    projects: [
      "ExpressJS API Optimization",
      "Schema Refactoring",
      "Query Performance Tuning",
    ],
    skills: [
      "Node.js",
      "Express.js",
      "TypeScript",
      "Database Optimization",
      "MongoDB",
    ],
  },
  {
    title: "Zyllem",
    role: "Frontend Developer",
    period: "Dec 2023 - Dec 2024 · 1 yr 1 mo",
    location: "Singapore · Remote",
    type: "Full-time",
    description:
      "Refactoring of components, directives and modules from Angular v7 to v18 and implemented design patterns for the version upgrade of the system. Participation with code reviews. Fixing assigned tickets for bugs and new features. Implemented and created calendar view using @event-calendar npm Svelte native and convert it to Angular to reduce cost instead of subscribing to paid calendar libraries. Collaboration with the backend team for new features and bug fixes.",
    projects: [
      "Angular 7→18 Upgrade",
      "Custom Calendar Component",
      "Code Review System",
    ],
    skills: [
      "Angular",
      "TypeScript",
      "JavaScript",
      "RESTful APIs",
      "Git",
      "Jira",
      "Svelte",
    ],
  },
  {
    title: "Nuclear Brain",
    role: "Junior Full-Stack Web Developer",
    period: "Dec 2022 - Dec 2023 · 1 yr 1 mo",
    location: "Remote",
    type: "Full-time",
    description:
      "Finished and fixed an email server for the company. Implemented real time progress for sending emails and uploading excel files for recipients list using Socket.io. Fixed UI issues such as customer counts, customer lists. Integrated Unlayer API as the campaign editor. Upgraded Angular version from v8 to v16. Fixed typescripting for all of the objects as it was coded using any type. Removal of html based bootstrap forms to BsModal library. Created Email List segmentation. Back end with ExpressJS, aligned with functions added on the front end. Deployment to AWS EC2 for the back end using elastic beanstalk. Deployment to S3 for front end using bundled js. Converted forms, navigation and tree list to Angular Material.",
    projects: [
      "Email Server Implementation",
      "Unlayer API Integration",
      "Email List Segmentation",
      "AWS Deployment",
    ],
    skills: [
      "Angular",
      "Express.js",
      "TypeScript",
      "Socket.io",
      "AWS EC2",
      "AWS S3",
      "Unlayer API",
      "Angular Material",
    ],
  },
  {
    title: "Volli Bellingham",
    role: "Junior Mobile and Web Application Developer",
    period: "May 2022 - Dec 2022 · 8 mos",
    location: "Remote",
    type: "Full-time",
    description:
      "Created appealing UI for the mobile app. Implemented chat feature for the app (customer to customer). Fixed bugs on the app and the web app. Implemented upload photo function.",
    projects: [
      "Mobile App UI Design",
      "Customer Chat Feature",
      "Photo Upload Functionality",
    ],
    skills: ["Angular", "Flutter", "Mobile Development", "UI/UX Design"],
  },
];
