export const characters = [
  {
    id: "king",
    name: "The King",
    image: "/profile/king.webp",
    title: "Royal Sovereign",
    subtitle: "Full-Stack Developer | Angular | NestJS | NodeJS",
  },
  {
    id: "warrior",
    name: "The Warrior",
    image: "/profile/warrior.webp",
    title: "Blade Master",
    subtitle: "ReactJS Warrior | React Native | Flutter | Frontend Champion",
  },
  {
    id: "archer",
    name: "The Archer",
    image: "/profile/archer.webp",
    title: "Marksman",
    subtitle: "TypeScript Archer | Precision Code | Clean Architecture",
  },
  {
    id: "wizard",
    name: "The Wizard",
    image: "/profile/wizard.webp",
    title: "Arcane Sage",
    subtitle: "NestJS Wizard | API Sorcery | Backend Enchantment",
  },
  {
    id: "alchemist",
    name: "The Alchemist",
    image: "/profile/alchemist.webp",
    title: "Potion Master",
    subtitle: "Expo Alchemist | Mobile Brewing | Cross-Platform Potions",
  },
  {
    id: "architect",
    name: "The Architect",
    image: "/profile/architect.webp",
    title: "Cathedral Builder",
    subtitle: "System Architect | Scalable Design | Enterprise Solutions",
  },
  {
    id: "blacksmith",
    name: "The Blacksmith",
    image: "/profile/blacksmith.webp",
    title: "Forge Master",
    subtitle: "NodeJS Forge | Backend Smithing | API Crafting",
  },
  {
    id: "farmer",
    name: "The Farmer",
    image: "/profile/farmer.webp",
    title: "Land Steward",
    subtitle: "React Native Farmer | Mobile Harvest | Cross-Platform Crops",
  },
  {
    id: "merchant",
    name: "The Merchant",
    image: "/profile/merchant.webp",
    title: "Trade Baron",
    subtitle: "Full-Stack Merchant | Value Trading | Solution Broker",
  },
  {
    id: "villager",
    name: "The Villager",
    image: "/profile/villager.webp",
    title: "Common Folk",
    subtitle: "Bachelor's in IT | Versatile Coder | Jack of All Trades",
  },
];
