import { MonsterConfig } from "@/monsters_modules";
import * as THREE from "three";

export const golelingConfigs: MonsterConfig[] = [
    {
        name: "Goleling",
        modelPath: "/monsters/Goleling.glb",
        position: new THREE.Vector3(32, -0.18, 70),
        scale: 0.5,
        movement: "patrol-fly",
        movementParams: {
            patrolPoints: [
                new THREE.Vector3(32, 2.5, 70),
                new THREE.Vector3(28, 2.5, 75),
                new THREE.Vector3(25, 2.5, 68),
                new THREE.Vector3(30, 2.5, 62),
                new THREE.Vector3(36, 2.5, 65),
                new THREE.Vector3(38, 2.5, 72),
                new THREE.Vector3(35, 2.5, 78),
                new THREE.Vector3(32, 2.5, 70),
            ],
            speed: 1.2,
            flyHeight: 2.5,
            hoverSpeed: 2,
        },
    },
    {
        name: "Goleling",
        modelPath: "/monsters/Goleling.glb",
        position: new THREE.Vector3(-25, -0.18, 55),
        scale: 0.5,
        movement: "patrol-fly",
        movementParams: {
            patrolPoints: [
                new THREE.Vector3(-25, 2.5, 55),
                new THREE.Vector3(-20, 2.5, 60),
                new THREE.Vector3(-22, 2.5, 48),
                new THREE.Vector3(-30, 2.5, 52),
                new THREE.Vector3(-28, 2.5, 62),
                new THREE.Vector3(-32, 2.5, 58),
                new THREE.Vector3(-25, 2.5, 55),
            ],
            speed: 1.1,
            flyHeight: 2.5,
            hoverSpeed: 1.8,
        },
    },
    {
        name: "Goleling",
        modelPath: "/monsters/Goleling.glb",
        position: new THREE.Vector3(15, -0.18, -85),
        scale: 0.5,
        movement: "patrol-fly",
        movementParams: {
            patrolPoints: [
                new THREE.Vector3(15, 2.5, -85),
                new THREE.Vector3(10, 2.5, -78),
                new THREE.Vector3(20, 2.5, -80),
                new THREE.Vector3(18, 2.5, -90),
                new THREE.Vector3(8, 2.5, -88),
                new THREE.Vector3(12, 2.5, -82),
                new THREE.Vector3(15, 2.5, -85),
            ],
            speed: 1.0,
            flyHeight: 2.5,
            hoverSpeed: 1.5,
        },
    },
    {
        name: "Goleling",
        modelPath: "/monsters/Goleling.glb",
        position: new THREE.Vector3(-20, -0.18, -60),
        scale: 0.5,
        movement: "patrol-fly",
        movementParams: {
            patrolPoints: [
                new THREE.Vector3(-20, 2.5, -60),
                new THREE.Vector3(-25, 2.5, -65),
                new THREE.Vector3(-15, 2.5, -68),
                new THREE.Vector3(-18, 2.5, -55),
                new THREE.Vector3(-28, 2.5, -58),
                new THREE.Vector3(-22, 2.5, -70),
                new THREE.Vector3(-20, 2.5, -60),
            ],
            speed: 1.3,
            flyHeight: 2.5,
            hoverSpeed: 2.2,
        },
    },
    {
        name: "Goleling",
        modelPath: "/monsters/Goleling.glb",
        position: new THREE.Vector3(0, -0.18, 85),
        scale: 0.5,
        movement: "patrol-fly",
        movementParams: {
            patrolPoints: [
                new THREE.Vector3(0, 2.5, 85),
                new THREE.Vector3(-5, 2.5, 80),
                new THREE.Vector3(5, 2.5, 82),
                new THREE.Vector3(3, 2.5, 90),
                new THREE.Vector3(-3, 2.5, 88),
                new THREE.Vector3(0, 2.5, 85),
            ],
            speed: 0.9,
            flyHeight: 2.5,
            hoverSpeed: 1.3,
        },
    },
    {
        name: "Goleling Evolved",
        modelPath: "/monsters/Goleling Evolved.glb",
        position: new THREE.Vector3(32, -0.18, 70),
        scale: 0.5,
        movement: "patrol-fly",
        movementParams: {
            patrolPoints: [
                new THREE.Vector3(32, 3.5, 70),
                new THREE.Vector3(28, 3.5, 75),
                new THREE.Vector3(25, 3.5, 68),
                new THREE.Vector3(30, 3.5, 62),
                new THREE.Vector3(36, 3.5, 65),
                new THREE.Vector3(38, 3.5, 72),
                new THREE.Vector3(35, 3.5, 78),
                new THREE.Vector3(32, 3.5, 70),
            ],
            speed: 1.6,
            flyHeight: 3.5,
            hoverSpeed: 2,
        },
    },
];